# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-12 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0005_auto_20200112_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='cuisines',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='price',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='tablebooking',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='website',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
