# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-13 10:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0007_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.Category'),
            preserve_default=False,
        ),
    ]
